-- Ledger database schema
-- Run this in Supabase SQL Editor.
create table if not exists public.portfolio_holdings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  coin_id text not null,
  symbol text not null,
  name text not null,
  quantity numeric(30,12) not null check (quantity >= 0),
  avg_buy_price numeric(30,8) not null check (avg_buy_price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, coin_id)
);
alter table public.portfolio_holdings enable row level security;
revoke all on table public.portfolio_holdings from anon;
grant select, insert, update, delete on table public.portfolio_holdings to authenticated;
drop policy if exists "Users can view their own holdings" on public.portfolio_holdings;
create policy "Users can view their own holdings" on public.portfolio_holdings for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "Users can insert their own holdings" on public.portfolio_holdings;
create policy "Users can insert their own holdings" on public.portfolio_holdings for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "Users can update their own holdings" on public.portfolio_holdings;
create policy "Users can update their own holdings" on public.portfolio_holdings for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users can delete their own holdings" on public.portfolio_holdings;
create policy "Users can delete their own holdings" on public.portfolio_holdings for delete to authenticated using ((select auth.uid()) = user_id);
create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;
drop trigger if exists portfolio_holdings_updated_at on public.portfolio_holdings;
create trigger portfolio_holdings_updated_at before update on public.portfolio_holdings for each row execute function public.set_updated_at();
